// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzhyQPv4-JMc2aA2QBdddeH9oTMz4Rl0',
    appId: '1:79459458360:android:70a6cb7d81f99f65f2f5cd',
    messagingSenderId: '79459458360',
    projectId: 'gymple-c8711',
    databaseURL: 'https://gymple-c8711-default-rtdb.firebaseio.com',
    storageBucket: 'gymple-c8711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB8Bi77MlyX933r1Np53UOXBBFFwmCveM',
    appId: '1:79459458360:ios:efdfceba327466eaf2f5cd',
    messagingSenderId: '79459458360',
    projectId: 'gymple-c8711',
    databaseURL: 'https://gymple-c8711-default-rtdb.firebaseio.com',
    storageBucket: 'gymple-c8711.appspot.com',
    iosClientId: '79459458360-0qe1duc4543m98sj5hl2tv6lnh2p0nsi.apps.googleusercontent.com',
    iosBundleId: 'com.developeek.realtimeGym',
  );
}
